package de.uniba.sme.bambirds.feedback;

public enum EvaluationCriteria{
POINTSGAINEDTOOLOW, PIGSHITBUTNOTENOUGHPOINTS, POINTDISTRIBUTIONNOTGOOD, NOTMUCHMOVEDANDNOPIGS, NOTMUCHMOVEDBUTPIGS, OBJECTSMOVEDDISTRIBUTIONNOTGOOD, NEARMISSLIKELY
}