// THIS FILE WAS AUTOMATICALLY GENERATED BY 'src/Python/decision_tree/decision_tree.py'

package level_selection.model_representation;

public class LinearRegressor {
public static double[] predict(int max_score, int num_birds, int num_destroyable_objects, int num_generated_shots, int num_line_segments_hills, int num_pigs, int num_strategies, int num_times_played, int numerical_strategies) {
	return new double[] {max_score*0.15227064867354104
		 + num_birds*1228.827795346745
		 + num_destroyable_objects*553.9227825071191
		 + num_generated_shots*-9.337737050159376
		 + num_line_segments_hills*69.21711280060018
		 + num_pigs*3942.1382051684877
		 + num_strategies*97.5635121174129
		 + num_times_played*-1082.3537035296783
		 + numerical_strategies*-18.6386696033793
		};
}
}