package de.uniba.sme.bambirds.common.objects;

public enum GameState {
	UNKNOWN, MAIN_MENU, EPISODE_MENU, LEVEL_SELECTION, LOADING, PLAYING, WON, LOST, NEWTESTSET, NEWTRAININGSET,
	RESUMETRAINING, NEWTRIAL, REQUESTNOVELTYLIKELIHOOD, EVALUATION_TERMINATED
}