/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.uniba.sme.bambirds;

import org.junit.Test;
import static org.junit.Assert.*;

public class BamBirdsTest {
    @Test 
    public void testBamBirds() {
        fail("Not tests yet");
    }
}
